apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "pix-new"
  description: "A cool quarkus app"
  annotations:
    argocd/app-name: pix-dev
    backstage.io/kubernetes-id: pix
    backstage.io/kubernetes-namespace: pix-dev
    janus-idp.io/tekton-enabled : 'true'
    backstage.io/source-location: url:https://gitlab-gitlab.apps.cluster-2wtdg.sandbox648.opentlc.com/development/pix
    backstage.io/techdocs-ref: url:https://gitlab-gitlab.apps.cluster-2wtdg.sandbox648.opentlc.com/development/pix
    gitlab.com/project-slug: development/pix
    quay.io/repository-slug: "/pix"
  tags:
    - java
    - quarkus
  links:
    - url: https://devspaces.apps.cluster-2wtdg.sandbox648.opentlc.com/#https://gitlab-gitlab.apps.cluster-2wtdg.sandbox648.opentlc.com/development/pix
      title: OpenShift Dev Spaces (VS Code)
      icon: web
    - url: https://devspaces.apps.cluster-2wtdg.sandbox648.opentlc.com/#https://gitlab-gitlab.apps.cluster-2wtdg.sandbox648.opentlc.com/development/pix?che-editor=che-incubator/che-idea/latest
      title: OpenShift Dev Spaces (JetBrains IntelliJ)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: group:pagamentos
  providesApis:
    - "pix"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: "pix"
  description: "A cool quarkus app"
spec:
  type: openapi
  lifecycle: production
  owner: user:marta
  definition:
    $text: ./openapi.yaml
